/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Antonio' at '1/23/16 3:54 PM' with Gradle 2.6
 *
 * @author Antonio, @date 1/23/16 3:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
